/**
 * 塔罗牌 78 张完整牌组数据
 * 大阿卡纳 22 张 + 小阿卡纳 56 张（权杖/圣杯/宝剑/星币 各14张）
 * 每张牌含正位/逆位关键词，用于抽牌展示和传给 AI 做解读上下文
 */
window.TAROT_DECK = [
  // ── 大阿卡纳 Major Arcana (22) ──
  { id:'m00', name:'愚者', name_en:'The Fool', arcana:'major', upright:['新的开始','冒险','天真','自由'], reversed:['鲁莽','冒进','缺乏方向'] },
  { id:'m01', name:'魔术师', name_en:'The Magician', arcana:'major', upright:['创造力','行动力','资源整合'], reversed:['操纵','能力未发挥','欺骗'] },
  { id:'m02', name:'女祭司', name_en:'The High Priestess', arcana:'major', upright:['直觉','潜意识','神秘'], reversed:['压抑直觉','秘密','疏离'] },
  { id:'m03', name:'皇后', name_en:'The Empress', arcana:'major', upright:['丰饶','滋养','创造','母性'], reversed:['过度依赖','停滞','忽视自我'] },
  { id:'m04', name:'皇帝', name_en:'The Emperor', arcana:'major', upright:['权威','结构','掌控','稳定'], reversed:['专制','固执','失控'] },
  { id:'m05', name:'教皇', name_en:'The Hierophant', arcana:'major', upright:['传统','信仰','指导','规范'], reversed:['教条','叛逆','打破常规'] },
  { id:'m06', name:'恋人', name_en:'The Lovers', arcana:'major', upright:['结合','选择','和谐关系'], reversed:['关系失衡','犹豫不决','分离'] },
  { id:'m07', name:'战车', name_en:'The Chariot', arcana:'major', upright:['意志力','胜利','前进','掌控局面'], reversed:['方向迷失','缺乏自制','受阻'] },
  { id:'m08', name:'力量', name_en:'Strength', arcana:'major', upright:['内在力量','勇气','耐心','柔韧'], reversed:['自我怀疑','软弱','失控'] },
  { id:'m09', name:'隐者', name_en:'The Hermit', arcana:'major', upright:['内省','独处','智慧','寻找答案'], reversed:['孤立','逃避','迷失方向'] },
  { id:'m10', name:'命运之轮', name_en:'Wheel of Fortune', arcana:'major', upright:['转折','命运','机遇','周期'], reversed:['厄运','失控','抗拒改变'] },
  { id:'m11', name:'正义', name_en:'Justice', arcana:'major', upright:['公平','真相','因果','责任'], reversed:['不公','逃避责任','偏见'] },
  { id:'m12', name:'倒吊人', name_en:'The Hanged Man', arcana:'major', upright:['牺牲','换位思考','暂停','顿悟'], reversed:['拖延','抗拒','徒劳牺牲'] },
  { id:'m13', name:'死神', name_en:'Death', arcana:'major', upright:['结束','转变','重生','放下'], reversed:['抗拒改变','停滞','恐惧结束'] },
  { id:'m14', name:'节制', name_en:'Temperance', arcana:'major', upright:['平衡','调和','耐心','中庸'], reversed:['失衡','过度','冲突'] },
  { id:'m15', name:'恶魔', name_en:'The Devil', arcana:'major', upright:['束缚','欲望','依附','阴影面'], reversed:['挣脱束缚','觉察','释放'] },
  { id:'m16', name:'高塔', name_en:'The Tower', arcana:'major', upright:['剧变','崩塌','顿悟','解放'], reversed:['逃避崩塌','延迟的灾难','内在动荡'] },
  { id:'m17', name:'星星', name_en:'The Star', arcana:'major', upright:['希望','疗愈','灵感','信念'], reversed:['失望','缺乏信心','迷茫'] },
  { id:'m18', name:'月亮', name_en:'The Moon', arcana:'major', upright:['潜意识','幻觉','不安','直觉'], reversed:['真相浮现','走出困惑','释放恐惧'] },
  { id:'m19', name:'太阳', name_en:'The Sun', arcana:'major', upright:['喜悦','成功','活力','真实'], reversed:['短暂的阴霾','过度乐观','延迟的喜悦'] },
  { id:'m20', name:'审判', name_en:'Judgement', arcana:'major', upright:['觉醒','重生','反思','召唤'], reversed:['自我怀疑','逃避召唤','拖延决定'] },
  { id:'m21', name:'世界', name_en:'The World', arcana:'major', upright:['完成','圆满','整合','成就'], reversed:['未完成','缺乏闭环','延迟的圆满'] },

  // ── 小阿卡纳：权杖 Wands (14, 行动/热情/事业) ──
  { id:'w01', name:'权杖首牌', name_en:'Ace of Wands', arcana:'wands', upright:['新灵感','热情迸发','创造契机'], reversed:['延迟','缺乏方向','热情消退'] },
  { id:'w02', name:'权杖二', name_en:'Two of Wands', arcana:'wands', upright:['规划未来','个人力量','远见'], reversed:['犹豫不决','缺乏计划'] },
  { id:'w03', name:'权杖三', name_en:'Three of Wands', arcana:'wands', upright:['扩展','远见','等待成果'], reversed:['延误','缺乏远见'] },
  { id:'w04', name:'权杖四', name_en:'Four of Wands', arcana:'wands', upright:['庆祝','和谐','归属感'], reversed:['不稳定','缺乏支持'] },
  { id:'w05', name:'权杖五', name_en:'Five of Wands', arcana:'wands', upright:['竞争','冲突','挑战'], reversed:['逃避冲突','内部纷争平息'] },
  { id:'w06', name:'权杖六', name_en:'Six of Wands', arcana:'wands', upright:['胜利','认可','自信'], reversed:['缺乏认可','自负'] },
  { id:'w07', name:'权杖七', name_en:'Seven of Wands', arcana:'wands', upright:['坚持立场','防御','勇气'], reversed:['压力过大','放弃立场'] },
  { id:'w08', name:'权杖八', name_en:'Eight of Wands', arcana:'wands', upright:['迅速行动','进展','消息'], reversed:['延迟','受阻的沟通'] },
  { id:'w09', name:'权杖九', name_en:'Nine of Wands', arcana:'wands', upright:['坚韧','戒备','最后一搏'], reversed:['疲惫','过度防御'] },
  { id:'w10', name:'权杖十', name_en:'Ten of Wands', arcana:'wands', upright:['负重前行','责任','压力'], reversed:['卸下重担','委托他人'] },
  { id:'w11', name:'权杖侍从', name_en:'Page of Wands', arcana:'wands', upright:['探索精神','热情','新消息'], reversed:['冲动','缺乏方向'] },
  { id:'w12', name:'权杖骑士', name_en:'Knight of Wands', arcana:'wands', upright:['冒险','冲劲','行动派'], reversed:['鲁莽','半途而废'] },
  { id:'w13', name:'权杖皇后', name_en:'Queen of Wands', arcana:'wands', upright:['自信','独立','感染力'], reversed:['嫉妒','缺乏安全感'] },
  { id:'w14', name:'权杖国王', name_en:'King of Wands', arcana:'wands', upright:['领导力','远见','魄力'], reversed:['专断','缺乏耐心'] },

  // ── 小阿卡纳：圣杯 Cups (14, 情感/关系/内心) ──
  { id:'c01', name:'圣杯首牌', name_en:'Ace of Cups', arcana:'cups', upright:['新的情感','爱意萌生','直觉开启'], reversed:['情感压抑','错失机会'] },
  { id:'c02', name:'圣杯二', name_en:'Two of Cups', arcana:'cups', upright:['连结','伙伴关系','相互吸引'], reversed:['关系失衡','误解'] },
  { id:'c03', name:'圣杯三', name_en:'Three of Cups', arcana:'cups', upright:['友谊','庆祝','共同喜悦'], reversed:['过度放纵','八卦纷争'] },
  { id:'c04', name:'圣杯四', name_en:'Four of Cups', arcana:'cups', upright:['冷漠','沉思','错失良机'], reversed:['觉醒','重新关注'] },
  { id:'c05', name:'圣杯五', name_en:'Five of Cups', arcana:'cups', upright:['失落','悔恨','聚焦损失'], reversed:['接受','走出悲伤'] },
  { id:'c06', name:'圣杯六', name_en:'Six of Cups', arcana:'cups', upright:['怀旧','纯真','重逢'], reversed:['活在过去','天真被利用'] },
  { id:'c07', name:'圣杯七', name_en:'Seven of Cups', arcana:'cups', upright:['幻想','选择过多','白日梦'], reversed:['清晰','做出抉择'] },
  { id:'c08', name:'圣杯八', name_en:'Eight of Cups', arcana:'cups', upright:['离开','寻求更深意义','放手'], reversed:['犹豫离开','逃避现实'] },
  { id:'c09', name:'圣杯九', name_en:'Nine of Cups', arcana:'cups', upright:['满足','愿望成真','情感满溢'], reversed:['过度享乐','表面满足'] },
  { id:'c10', name:'圣杯十', name_en:'Ten of Cups', arcana:'cups', upright:['圆满','家庭和睦','情感和谐'], reversed:['关系裂痕','理想化的破灭'] },
  { id:'c11', name:'圣杯侍从', name_en:'Page of Cups', arcana:'cups', upright:['情感讯息','直觉萌芽','创造力'], reversed:['情绪化','不成熟的表达'] },
  { id:'c12', name:'圣杯骑士', name_en:'Knight of Cups', arcana:'cups', upright:['浪漫','理想主义','情感追求'], reversed:['不切实际','情绪波动'] },
  { id:'c13', name:'圣杯皇后', name_en:'Queen of Cups', arcana:'cups', upright:['共情','直觉','情感成熟'], reversed:['过度敏感','情绪淹没'] },
  { id:'c14', name:'圣杯国王', name_en:'King of Cups', arcana:'cups', upright:['情感掌控','包容','智慧'], reversed:['情绪压抑','操纵他人情感'] },

  // ── 小阿卡纳：宝剑 Swords (14, 思维/沟通/冲突) ──
  { id:'s01', name:'宝剑首牌', name_en:'Ace of Swords', arcana:'swords', upright:['清晰思路','突破','真相浮现'], reversed:['混乱思绪','误判'] },
  { id:'s02', name:'宝剑二', name_en:'Two of Swords', arcana:'swords', upright:['僵局','两难','逃避决定'], reversed:['打破僵局','面对现实'] },
  { id:'s03', name:'宝剑三', name_en:'Three of Swords', arcana:'swords', upright:['心碎','伤痛','背叛'], reversed:['疗愈','走出伤痛'] },
  { id:'s04', name:'宝剑四', name_en:'Four of Swords', arcana:'swords', upright:['休整','沉淀','恢复'], reversed:['被迫复出','停滞的恢复'] },
  { id:'s05', name:'宝剑五', name_en:'Five of Swords', arcana:'swords', upright:['冲突','以胜为耻','紧张关系'], reversed:['和解','放下争执'] },
  { id:'s06', name:'宝剑六', name_en:'Six of Swords', arcana:'swords', upright:['过渡','离开困境','走向平静'], reversed:['滞留原地','未解决的问题'] },
  { id:'s07', name:'宝剑七', name_en:'Seven of Swords', arcana:'swords', upright:['策略','独自行动','隐瞒'], reversed:['坦白','策略失败'] },
  { id:'s08', name:'宝剑八', name_en:'Eight of Swords', arcana:'swords', upright:['受限','自我设限','困境感'], reversed:['挣脱束缚','找到出路'] },
  { id:'s09', name:'宝剑九', name_en:'Nine of Swords', arcana:'swords', upright:['焦虑','失眠','内心煎熬'], reversed:['走出焦虑','释放恐惧'] },
  { id:'s10', name:'宝剑十', name_en:'Ten of Swords', arcana:'swords', upright:['谷底','终结','背叛的伤痛'], reversed:['触底反弹','缓慢恢复'] },
  { id:'s11', name:'宝剑侍从', name_en:'Page of Swords', arcana:'swords', upright:['好奇心','警觉','新想法'], reversed:['鲁莽言语','散播是非'] },
  { id:'s12', name:'宝剑骑士', name_en:'Knight of Swords', arcana:'swords', upright:['果断','直接','雷厉风行'], reversed:['冲动行事','缺乏考虑'] },
  { id:'s13', name:'宝剑皇后', name_en:'Queen of Swords', arcana:'swords', upright:['理性','独立','清晰界限'], reversed:['尖锐','情感疏离'] },
  { id:'s14', name:'宝剑国王', name_en:'King of Swords', arcana:'swords', upright:['权威','逻辑','公正判断'], reversed:['专断','冷酷无情'] },

  // ── 小阿卡纳：星币 Pentacles (14, 现实/物质/成长) ──
  { id:'p01', name:'星币首牌', name_en:'Ace of Pentacles', arcana:'pentacles', upright:['新机会','物质开端','稳固基础'], reversed:['错失机会','根基不稳'] },
  { id:'p02', name:'星币二', name_en:'Two of Pentacles', arcana:'pentacles', upright:['平衡取舍','灵活应变','多线并进'], reversed:['失衡','顾此失彼'] },
  { id:'p03', name:'星币三', name_en:'Three of Pentacles', arcana:'pentacles', upright:['协作','技能精进','团队成果'], reversed:['缺乏协作','品质欠佳'] },
  { id:'p04', name:'星币四', name_en:'Four of Pentacles', arcana:'pentacles', upright:['掌控','稳固','安全感'], reversed:['过度控制','物质执着'] },
  { id:'p05', name:'星币五', name_en:'Five of Pentacles', arcana:'pentacles', upright:['困境','匮乏感','孤立无援'], reversed:['走出困境','重获支持'] },
  { id:'p06', name:'星币六', name_en:'Six of Pentacles', arcana:'pentacles', upright:['给予','分享','互惠'], reversed:['不平等','附带条件的施与'] },
  { id:'p07', name:'星币七', name_en:'Seven of Pentacles', arcana:'pentacles', upright:['耐心等待','长期投入','评估成果'], reversed:['缺乏耐心','投入无回报'] },
  { id:'p08', name:'星币八', name_en:'Eight of Pentacles', arcana:'pentacles', upright:['精进','专注','踏实付出'], reversed:['敷衍了事','缺乏动力'] },
  { id:'p09', name:'星币九', name_en:'Nine of Pentacles', arcana:'pentacles', upright:['独立','富足','自我实现'], reversed:['过度依赖物质','孤独'] },
  { id:'p10', name:'星币十', name_en:'Ten of Pentacles', arcana:'pentacles', upright:['传承','家族财富','长远稳定'], reversed:['家庭纷争','财务不稳'] },
  { id:'p11', name:'星币侍从', name_en:'Page of Pentacles', arcana:'pentacles', upright:['务实学习','脚踏实地','新机遇'], reversed:['缺乏规划','三分钟热度'] },
  { id:'p12', name:'星币骑士', name_en:'Knight of Pentacles', arcana:'pentacles', upright:['稳健','勤勉','按部就班'], reversed:['固执','停滞不前'] },
  { id:'p13', name:'星币皇后', name_en:'Queen of Pentacles', arcana:'pentacles', upright:['滋养','务实','温暖踏实'], reversed:['过度操劳','忽视自我'] },
  { id:'p14', name:'星币国王', name_en:'King of Pentacles', arcana:'pentacles', upright:['富足','稳健领导','物质成就'], reversed:['贪婪','物质至上'] }
];
